# Generated by Django 5.0.2 on 2024-04-22 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='content',
            new_name='message',
        ),
    ]
